### ISSUE TITLE
Need dir.sh for Deployments to Unix

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#10]
Build 339: Attempting to deploy an Application to a Unix server with the Get Directory procedure/function in a Custom Action returns:

Runtime error at line 4: Failed to open file "C:\Program Files\OpenMake Software\Release Engineer\Engine\scripts\dir.sh" for read

Release Engineer needs a dir.sh that is equivilant to the Windows sh.vbs located in C:\Program Files\OpenMake Software\Release Engineer\Engine\scripts

**Comment by sbtaylor15** [comment]
duplicate
