### ISSUE TITLE
Problems with Deploy Sequentially in a Component

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#103]
Build 379: Components General tab shows the field 'Deploy Sequentially' with a value of '[object Object]'. Also, click on the pencil icon to show the edit window, there is no field for 'Deploy Sequentially'.

**Comment by pgibbs-openmake** [comment]
Have you made sure you've done a refresh (ctrl-F5 or similar)? That sounds like the client javascript code is behind the server-side stuff.

**Comment by rightker** [comment]
Sure did.

**Comment by pgibbs-openmake** [comment]
Well it works fine on my instance - the client side stuff is handled by GetSummary.js which is definitely in the git commit.

Screenshot:

<img width="1153" alt="screen shot 2016-05-04 at 00 03 34" src="https://cloud.githubusercontent.com/assets/14827319/15000996/d2a4f3d8-118b-11e6-99ff-aab73f5e6471.png">

**Comment by pgibbs-openmake** [comment]
Did a clean install of the latest Linux build this morning and this is working fine for me. Can you confirm this is still an issue?

**Comment by rightker** [comment]
Did a clean install and refreshed the browser. Still an issue in Chrome, so I tried it in Firefox and it works fine there.

**Comment by pgibbs-openmake** [comment]
Works fine in my Chrome instance.

**Comment by rightker** [comment]
Restarted the server and it works fine in Chrome now. Closing this issue.
