### ISSUE TITLE
server status fails when credential is set to only have userid and no password

### ISSUE THREAD

**Issue by sbtaylor15** [OpenMake-Software/ReleaseEngineer#104]
no even making it to dmtransfer

**Comment by pgibbs-openmake** [comment]
This has never been supported. We're going to have to do some rework to handle this scenario. I suspect the engine will have issues with this setup as well.

**Comment by pgibbs-openmake** [comment]
Made a change to pass through "" as a valid password. Rebuild and retest required.

**Comment by sbtaylor15** [comment]
Passed in 5/4 build
