### ISSUE TITLE
Improve how Repository attributes are handled in Component Items

### ISSUE THREAD

**Issue by quinnbailey** [OpenMake-Software/ReleaseEngineer#106]
Three items here:

1. If somehow you are able to set the 'filepath' attribute at the Component Item level (e.g. filepath is not defined at the repository level or is set to 'override'), if you make a change to the repository such that 'filepath' is no longer able to be set (or seen) in the Component Item, that attribute is still set at the Component Item level and will cause deployment errors -  "filepath is not appendable".

2. There should be some sort of hint in the UI for defining Component Items that indicates the attributes that are related to the repository type you've selected.  As it is now, the attributes appear below the repository drop down but otherwise look like any other fields in the Component Item config.  My preference would be to have a box around those attributes with a heading that indicates these attributes are determined by the repository type you've selected.  Furthermore, if there are attributes set at the repository level, it would be helpful to be able to see those settings in the Component Item (greyed out or something so it's obvious they're not editable).

3. The 'Override' and 'Append' options for repository attributes should be renamed to 'Override-able' and 'Append-able' (dash or no dash, however you like), so the meaning of these options is more clear.

**Comment by pgibbs-openmake** [comment]
Fix in git - requires new build and retest.

**Comment by quinnbailey** [comment]
2 & 3 look good, will get to 1 tomorrow

**Comment by quinnbailey** [comment]
#1 is good, but 2 & 3 have a few things off.  

2 - This looks much better than before but I would still like to see the last item added: 

> if there are attributes set at the repository level, it would be helpful to be able to see those settings in the Component Item (greyed out or something so it's obvious they're not editable).

3 - These have been renamed on the repository page but not in the attribute dialog where these appear as checkboxes.

**Comment by pgibbs-openmake** [comment]
_"if there are attributes set at the repository level, it would be helpful to be able to see those settings in the Component Item (greyed out or something so it's obvious they're not editable)."_

That would actually be quite difficult to implement with the way things are coded at the moment. I'd prefer to park this one. It was a deliberate design decision to only show the fields that could be changed at a component item level (a) to simplify the end-user experience and prevent confusion (What is a Viewpath? Why is it greyed out?) and (b) for security (to prevent the users even seeing the other fields that control the repository).

3. - They're renamed on *my* attribute dialog (see screenshot). Which attribute dialog are you referring to?
<img width="1680" alt="screen shot 2016-05-05 at 18 21 06" src="https://cloud.githubusercontent.com/assets/14827319/15050942/3c89f89e-12ee-11e6-883d-cb7fad074606.png">

**Comment by quinnbailey** [comment]
I thought there might be a bit more work to change that viewing of inherited attributes, but if that's actually been deliberately designed that way then that does that.

For the second item, yes I'm seeing it now, not sure I wasn't able to see it before.

Closing ....
