### ISSUE TITLE
Go to this Application Version Hangs

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#108]
Build 379: Deploy menu -> Applications tab -> select an Application Base Version in the tree structure -> Versions tab -> right click on an Application Version and select Go to this Application Version, notice it hangs with "Loading..." message and never goes anywhere. Checked this on another server with another laptop with same results.

**Comment by sbtaylor15** [comment]
Retest.

**Comment by rightker** [comment]
Tested fix, works fine, closing this issue.
