### ISSUE TITLE
Creating or Modifying items that use pre/post actions takes exceptionally long

### ISSUE THREAD

**Issue by quinnbailey** [OpenMake-Software/ReleaseEngineer#109]
This includes Components, Component Items, Applications and Tasks (probably others too).  Apparently this is due to all the Ansible stuff that has been loaded taking forever to populate these lists but sometimes it goes so long that Chrome things the page is hung.  Not a great user experience.

**Comment by sbtaylor15** [comment]
Retest.  Cut down the number of Ansible roles imported.

**Comment by sbtaylor15** [comment]
Changing to 150 as the download count.
