### ISSUE TITLE
Need List of Objects within Tree Structure that can be Drag & Dropped

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#11]
Build 339: Dragging and dropping objects within the tree structure on the left side of Release Engineer varies from object to object. Need to know which should and shouldn't be able to, both for documentation and testing:

Can be D&D'd:
Components
Environments
Actions
Funcs & Procs
Domains
Users
Groups

Can't be D&D'd:
Applications
Releases
Servers
Notifiers
Repositories (throws msg "Not yet implimented")
Data Sources
Credentials
Component and Server Types

**Comment by sbtaylor15** [comment]
Are you just D&D from one domain to another for a specific object?

**Comment by rightker** [comment]
Yes. Tried one of each kind of object, and got a green check mark and it worked for the first list above, got a red check mark and it didn't work for the second list above.

**Comment by rightker** [comment]
Just tested every kind of object, all objects drag and drop except Applications, as they should. Redrawing shows objects still in place, and returning them to their original place and redrawing shows them correctly. Closing this issue.
