### ISSUE TITLE
Static Ansible Parameters should be in "Additional Command Line Switches"

### ISSUE THREAD

**Issue by pgibbs-openmake** [OpenMake-Software/ReleaseEngineer#111]
Parameters such as GalaxyRole, Target, AnsibleVariableFile and so on should not be "inputs" to the Ansible procedure since these are (a) always the same for every Ansible role, (b) should not be modifiable from the action editor and (c) having these extra fields to fill in for every Ansible Activity over-complicates things.

Instead of setting these in the fragment attributes, set them in "Additional Command Line Switches" which will remove them from the input parameters.

**Comment by sbtaylor15** [comment]
Retest
