### ISSUE TITLE
Nonsense Error Msg when Target Server is not Found

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#112]
Whenever a server is unavailable for any reason and a deployment fails, log shows "terminate called after throwing an instance of 'char const*'". Need to have an err msg that makes more sense.

**Comment by rightker** [comment]
Also happens when username/password is incorrect.

**Comment by pgibbs-openmake** [comment]
Fix is in git. Requires rebuild and retest.

**Comment by rightker** [comment]
Tested with bad hostname and again with bad Credential. Works fine. Closing this issue.
