### ISSUE TITLE
Need "Lifecycle Overview" changed to "Delivery Pipeline" in new doc

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#114]
Need to have "Lifecycle Overview" changed to "Delivery Pipeline" in the new document that will be placed with the online docs.

**Comment by sbtaylor15** [comment]
Update Web UI to use Delivery Pipeline.

**Comment by rightker** [comment]
This has been changed from Update Web UI to Delivery Pipeline throughout Application. Closing this issue.
