### ISSUE TITLE
Extra lines appear in Timeline for a new Server

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#115]
Adding a Server causes lines of information to appear in the Timeline tab that have nothing to do with the server. Looks like information for other Servers.

**Comment by rightker** [comment]
Adding a Component to the new Server via the Deployed Components tab, a new line appears in the list as expected, but instead of the current date and time, it shows a random date and time from the past, even for Components that have never been deployed to any Server.

**Comment by rightker** [comment]
Same thing happens with a new Application. A lot of lines appear in the Timeline tab dated prior to the creation date and time.

**Comment by pgibbs-openmake** [comment]
It will depend on what the "lines" refer to and what they are. Server timelines report data for the parent environment. Similarly, Application timelines contain details for their constituent components. Adding a component to an application will result in component timeline records appearing in the application timeline regardless of if the application has just been created.

Without knowledge of what the "lines of information" are, it is not possible to say if this is a bug or working as designed.

**Comment by rightker** [comment]
The Application was associated with the Environment several days before the creation of the Server. The Server was then added to the Environment. Activity is being reported for the Application going back several days, including the addition of Components to the Application. This seems like a lot of unnecessary information. And the fact that I'm testing by creating new objects only very recently makes me wonder how many "lines" will appear for "brand new shiny" objects with connections to "ancient" objects. Perhaps "tonnes of lines" will appear. Gadzooks!

**Comment by rightker** [comment]
Talked with Phil, this is as designed and is intended to show all history for trouble shooting purposes. All of the information seems to be accurate in the examples we looked at. Closing this issue.
