### ISSUE TITLE
Copy To Remote Doesn't appear to work

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#119]
Procedure of type Copy to Remote doesn't copy the file from the specified directory on the Release Engineer server to the /tmp directory on the target box as per the online docs. It also doesn't copy it from the specified directory on the Release Engineer server to an identically named directory on the target server.

**Comment by pgibbs-openmake** [comment]
It does execute though, right? Are you just saying you can't find it in /tmp after the event?

**Comment by rightker** [comment]
It doesn't appear in /tmp and there is also an error message in the place where the procedure gets called:

INFO: Starting deployment #289
INFO: Deploying Application "testApp76" into Environment "test76Environment"
/tmp/140734059935856.rsp: line 3: unexpected EOF while looking for matching `"'
/tmp/140734059935856.rsp: line 4: syntax error: unexpected end of file
INFO: Deploying Component test76Comp2
INFO: Checked out testFile1;0

**Comment by pgibbs-openmake** [comment]
Sounds like the copy shell commands have got syntax errors - but that would imply copy to remote is not working ... but it has been, right?

Looping Steve for his input...

**Comment by rightker** [comment]
There were other problems in the past that prevented proper testing, so no, not necessarily.

**Comment by sbtaylor15** [comment]
Fix in build 	20161214_641
