### ISSUE TITLE
Moving an Application From One Domain to Another leaves a Copy in the Original Folder

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#12]
Build 339: Select or create an Application in a Domain -> Create a Move Task to Move the Application to another Domain -> Move the Application to the other Domain, notice that there are now 2 Applications, 1 in each of the Domains.

**Comment by rightker** [comment]
Build 339

**Comment by sbtaylor15** [comment]
Are you move an application or application version?  The best practice is to the create a Application in the domain above, DEV, QA, PROD etc.  and create the application version in the lifecycle stages.  Then move the application versions through the lifecycle instead of moving the application.

**Comment by rightker** [comment]
Application Version. An Application behaves as expected.

**Comment by pgibbs-openmake** [comment]
Can we retest this? Versions now show under their parent applications regardless of the lifecycle status of the source and target domains.

**Comment by rightker** [comment]
Created a Domain and set "Contains Lifecycles" to Yes -> Created an Application within this new Domain-> Created 3 Lifecycle Domains within it named dev, test, prod -> Created a Version of the App -> Created a Move Task in the parent Domain and used it to move the Base App to the dev Domain, and the App disappeared, there is nothing in dev -> Created a new App -> Created a Version -> Moved the Version to dev, same results. Everything being moved to dev from the parent is disappearing.

**Comment by pgibbs-openmake** [comment]
Cannot reproduce. Followed exact steps and working fine on my version. Tested with Safari, Chrome and Firefox against Linux and Windows Servers.

**Comment by rightker** [comment]
Works fine for me, and the App used in the previous test now appears in the Domain (?)  Closing this issue.
