### ISSUE TITLE
foreach Loop Counter has Maximum Value First Time Through Loop 

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#121]
The Component has 3 Items named 'Comp Item 1', 'Comp Item 2', and 'Comp Item 3'. A loop is created in a Procedure that is part of an Action set as the Post Action for the Component. This is an attempt at printing the names of all the Component Items:

set items = ${component.items}; // get all Component Items for the current Component
   foreach(ci: $items) {
       echo "ci is $ci"; // first time thru grabs max value (2 in this case)
       echo "Component Item name = ${items[$ci].name}"; // echos 2 first time instead of 0
   }

Results are:
ci is 2
Component Item name = Comp Item 3
ci is 0
Component Item name = Comp Item 1
ci is 1
Component Item name = Comp Item 2

It would make more sense, and be less confusing to the customer, to have the results print out in the order of 0, 1, 2.

**Comment by pgibbs-openmake** [comment]
Fixed in latest engine code. Rebuild and retest required.

**Comment by rightker** [comment]
Fixed, tested and passed in QA version 379 on 6-30-2016.
