### ISSUE TITLE
Checkout and Transfer don't work

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#122]
Very simple example of Checkout and Transfer commands shown here:

using dropzone 'myDrop' {
  echo "Here we go";
  checkout (repository: 'deployTestRepo') ;
  echo "Here we are";
  transfer;
  echo "There we was";
}

Results appear several times, once for each Component, as:

INFO: Deploying Component testDeployComp using Custom Action testDeployAction
Here we go
Here we are
There we was
INFO: Return code is 0

So obviously nothing is happening.

**Comment by pgibbs-openmake** [comment]
When running "checkout" with a component on the stack (i.e.: during an action attached to a component) the checkout command would always perform a component-item checkout regardless of the parameters to checkout. This has been fixed - rebuild and retest is required.

**Comment by rightker** [comment]
Tested 7-13-2016, works. Closing this issue.

**Comment by rightker** [comment]
Overlooked this and hit 'Comment' instead of 'Close and Comment' when closing. Closing this now.
