### ISSUE TITLE
HTTP repository plugin bugs with bad paths

### ISSUE THREAD

**Issue by quinnbailey** [OpenMake-Software/ReleaseEngineer#125]
So a few issues I've observed with the HTTP plugin if you give it an incorrect path in your repo URI:
1. If the deployment file is present on the target, nothing will be delivered, but the file deployment shows up as a success with 'null' file MD5.
2. If there is a file present, the file is overwritten with a 0 byte file, but the file deployment shows up as a success with the MD5 of the zero byte file.

I'd say these are pretty critical issues because it reports success for failed deployments.

**Comment by quinnbailey** [comment]
In case it's a necessary condition to recreate, I'm using open-source Artifactory server v4.9.1 as my HTTP repo.

**Comment by pgibbs-openmake** [comment]
Fix applied to http repository code - rebuild and retest required.

**Comment by quinnbailey** [comment]
Now I'm seeing something a little stranger with the latest build.  I may or may not have things configured exactly the way it should be, but regardless the log says that my http repo file is found and delivered to the target server and it most definitely is not.  This file also does not appear in the Files tab which certainly indicates part of RE knows something is amiss, but still this is not being properly reported and there's no other helpful info as to why the file does not appear on the target.  Here's the logging:

INFO: Starting deployment #138
INFO: Deploying Application "Uptime" into Environment "TestEnv"
INFO: Deploying Component UptimeTomcat
INFO: Checked out artifactory/libs-snapshot-local/uptime/Uptime_61/uptime.war;0
INFO: Item "Item 1": Checked out 1 file(s) from repository "artifactory-snapshots"
INFO: Deploying Component UptimeTomcat to Server centos7-clone
INFO: Time taken 0.010000 seconds

**Comment by pgibbs-openmake** [comment]
Well, there's usually lines after "Deploying Component" which indicates the actual transfer to the target server. Like this (from my instance):

NFO: Starting deployment #2153
INFO: Deploying Application "GameOfLife" into Environment "AservoEnv"
INFO: Deploying Component GameOfLife
INFO: Checked out /qa/soap.jar;2
INFO: Checked out 1 file(s) from repository "httprep"
INFO: Deploying Component GameOfLife to Server aservo
INFO: Deployed File soap.jar -> aservo:C:\temp/soap.jar
INFO: Time taken 46.436001 seconds

So it looks like either it's still erroneously reporting that it's checked out the file uptime.war (when it hasn't) or something has happened between the checkout and the deploy.

I presume if you replace "uptime.war" in the component item with something that doesn't exist (like "thisdoesnotexist.war") then it reports 0 files checked out?

**Comment by sbtaylor15** [comment]
Working in 20161121_615
