### ISSUE TITLE
Remove Entry from Home Page's To Do List if a Related Task is Deleted

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#13]
If an entry appears in a User's Home Page To Do list concerning a specific Task, that entry should be removed from the To Do list if that Task is deleted. Or maybe the deletion of a Task should be prevented is there is a related item in a User's To Do list?

**Comment by sbtaylor15** [comment]
Probably deleting the task in the to-do list is the way to keep things tidy, since the object is deleted the task is no longer required.

**Comment by sbtaylor15** [comment]
Retest.

**Comment by rightker** [comment]
Created Request, Approve, and Deploy Tasks as admin, set up Access accordingly, logged out as admin, back in as kirk, right clicked Request Task and filled in comment, logged out and in as admin, To Do list for admin had the request entry in it. Deleted Request Task, To Do still had entry, deleted Approve Task, To Do still had entry. Deleted Deploy Task, still had entry in To Do list. (Deploy Task doesn't actually get deleted, but disappears from Domain and reappears on redraw).

**Comment by pgibbs-openmake** [comment]
Can you confirm what task the request task was linked to? The Deploy Task or the Approve Task?

**Comment by rightker** [comment]
Deploy.

**Comment by pgibbs-openmake** [comment]
Okay. But the Deploy task didn't get deleted - am I reading that right? Since once redrawn it's back again.

**Comment by rightker** [comment]
Yes. Although I looked around, and that particular one does, and another
doesn't. I'll need to look into that part of it a bit deeper.

**Comment by pgibbs-openmake** [comment]
Fix is in git - rebuild and retest required.

**Comment by rightker** [comment]
The Deploy Task is the Task that has to be deleted but the particular one chosen for the test can't be deleted. Phil discovered the problem. This requires change and a build.

**Comment by rightker** [comment]
Phil fixed problem with deleting Deployment Tasks. Tested feature where line in To Do list disappears if the Deployment Task is deleted. Works, closing this issue.
