### ISSUE TITLE
"Loading..." msg when clicking on Assigned Environments tab

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#134]
Deploy menu -> Applications tab -> Assigned Environments tab, locks up with "Loading..." message.

**Comment by pgibbs-openmake** [comment]
Can't reproduce. Need client console log.

**Comment by rightker** [comment]
Phil is looking into this, may be a problem with the DB and left over data.

**Comment by sbtaylor15** [comment]
Working in 20161121_615
