### ISSUE TITLE
Clicking on Server and then Defects tab causes everything to disappear

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#136]
Click on an Environment -> Click on a Server within the Environment -> There is a Defects tab showing the defects for the Applications that are associated with the Environment. Click on the Defects tab, notice all of the tabs disappear ->Click on the Servers tab, notice there is no Defects tab on the right.

**Comment by rightker** [comment]
Unable to recreate this. The data within the database was changed for another issue and may have affected this, not certain. Closing this issue.

**Comment by pgibbs-openmake** [comment]
I fixed this but forgot to update the issue.

**Comment by rightker** [comment]
Oh, cool, thanks.

**Comment by rightker** [comment]
Phil informed me that he fixed the issue and forgot to update github.
