### ISSUE TITLE
Notifier shows password in entry field and Properties tab

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#137]
Entering a new Notifier does not show asterisks, but rather the actual text, for the password field both in the password field when entering a new Notifier and in the Properties tab.

**Comment by pgibbs-openmake** [comment]
"password" is simply a generic property and is a "hang-over" from earlier releases. When creating notifiers in 7.6 and later, one should use a Credential object. We should probably remove username/password from the notifier properties in 7.7.

Incidentally, if you click the "encrypted" box, the property should be shown as asterisks on the properties tab as desired.

**Comment by rightker** [comment]
Tried encrypted, still shows as regular text.

**Comment by pgibbs-openmake** [comment]
Yes, it will. It shows as asterisks in the _properties_ tab (not in the entry box). As I said, password should not be a regular property - you can (and should) use a credential.

**Comment by sbtaylor15** [comment]
Working as expected.
