### ISSUE TITLE
Need to Have Creation Rights to Build Engines, Just Like Other Objects

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#140]
There are no Creation Rights for Groups for Build Engines, like all the other objects in RE.

**Comment by pgibbs-openmake** [comment]
There is an "access" tab for build engines which includes "View", "Change" and "Start Build Access" (for kicking off builds from RE).

**Comment by rightker** [comment]
Sorry, I meant 'Creation' Rights, as in Users & Groups menu -> Groups tab -> click on a Group -> Admin Rights tab, all of the objects with checkboxes; Users, User Groups, Domains, etc. Do we want to add Build Engines to this?

**Comment by pgibbs-openmake** [comment]
As, sorry. I see what you mean. Yes, we do. I'll sort that.

**Comment by rightker** [comment]
There appears to be extra Admin Rights in Users & Groups -> Groups -> Admin Rights, but no ability to scroll down to see what they are. This needs a scroll bar. Was 'Build Engines' added?

**Comment by pgibbs-openmake** [comment]
Build Engines were added yes. I've added a bit to the panel height to allow you to see "Build Engines". Retest required.

**Comment by rightker** [comment]
Perfect, closing this issue.
