### ISSUE TITLE
New Application Version Doesn't Inherit Bug Tracking Datasource from Base Version

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#141]
Use an existing Application Base Version with a Bug Tracking Datasource assigned to it -> Create an Application Version from it using a Create Version Task -> General tab in new Application Version, notice the Bug Tracking Datasource field is blank.

**Comment by pgibbs-openmake** [comment]
Already fixed that for Components (not in git yet though) so don't raise one for components until you've done a rebuild! :-)

**Comment by rightker** [comment]
Thanks for the heads up on that. I'll enter a bug so I remember to follow up and test the new version.

**Comment by rightker** [comment]
Fixed in 596, closing this bug.
