### ISSUE TITLE
Linked Task field for Request Tasks is Unintentionally Filled in When Edited

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#144]
Domains menu -> Domains tab -> Tasks tab -> Right Click in Tasks in this Domain and select Add Move Version Task, click OK, notice that the Link Task field in the Task Detail area is blank -> Click the Pencil Icon to edit the Move Task, notice there is no blank line in the drop down list for the Link Task, but rather the uppermost item in the list is in the field -> Click OK, notice that the uppermost item in the list now appears in the Linked Task field.

**Comment by pgibbs-openmake** [comment]
More significantly, there shouldn't be a "link task" field in a Move Version task. Linked tasks are only for request tasks.

Cannot reproduce this in either Safari or Firefox. Which browser are you using? Chrome?

**Comment by rightker** [comment]
Yes, Chrome.

**Comment by rightker** [comment]
Using Chrome.

**Comment by rightker** [comment]
Went back through all Tasks, and it happens to all the dropdown fields that contain Domains: Approval Domain for Approval Tasks, Move to Domain for Move Tasks, and Linked Task for Request Tasks.

**Comment by pgibbs-openmake** [comment]
That's deliberate design - there are no circumstances when a blank value is permitted in such a field. In other words, you cannot have an approval task with no approval domain. You cannot have a "move" task with no "target" domain. You cannot have a "request" task without specifying the task you're requesting. etc. On initial creation this field is blank and that will generate an error if the task is invoked but that's okay. But allowing a user to deliberately break the task post-creation is not good design.

Still a little concerned that the original defect says that the "Move Version" task is showing a "Link Task" field. Is this actually the case?

**Comment by rightker** [comment]
It's for a Request Task, not a Move Task, sorry. And it still works as I described. Closing this since it's not possible to assign a blank value post-creation.
