### ISSUE TITLE
Can't Delete an Application.

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#15]
Build 339: Created an Application, didn't create a Component for it, created an Application Version for it, deleted Application Version, Deleted Application, redraw, Application reappears in tree structure. Tried to delete it several times.

**Comment by sbtaylor15** [comment]
Did the Application Version reappear after the re-draw?

**Comment by rightker** [comment]
No, just the Application.

**Comment by sbtaylor15** [comment]
Retest

**Comment by sbtaylor15** [comment]
Passed in build 4/14
