### ISSUE TITLE
Defects Tab Exists for Servers Under Environments But Not By Themselves

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#152]
Defects Tab Exists for Servers Under Environments But Not By Themselves. Clicking on Defects Tab makes all tabs on the right side disappear.

**Comment by pgibbs-openmake** [comment]
Should be fixed now, retest required.

**Comment by rightker** [comment]
No defects tabs exist for Servers. Closing this issue.
