### ISSUE TITLE
Values in Component Type Field Are Not Shown In New Component

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#153]
Deploy menu -> Components tab -> Right click on a Domain -> Select "New Component in this Domain" -> Entering values into fields, notice that the Component Type field has no values to choose from. Saving the Component, then going back and editing it, shows values in the Component Type field. This is very similar to #135.

**Comment by sbtaylor15** [comment]
Fixed in 20161121_615

**Comment by rightker** [comment]
Works as described.
