### ISSUE TITLE
Delivery Pipeline Tab Appears In Too Many Places

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#154]
The Delivery Pipeline tab on the right side should only appear when clicking on Domains containing Lifecycle Domains, but instead appears throughout Release Engineer. (Should it also appear for Releases?)

**Comment by pgibbs-openmake** [comment]
When you say "instead appears throughout Release Engineer", what do you mean? Where is it showing? It should not appear for Releases since the Delivery Pipeline shows all apps and where they are in the pipeline both logically (which domain they are in) and physically (which environment they are deployed to). A "release" should show on the Delivery Pipeline alongside its constituent applications.

**Comment by rightker** [comment]
Deploy menu -> Components tab -> Delivery Pipeline appears in tabs on the right
End Points menu -> Environments tab -> Delivery Pipeline appears in tabs on the right
Flows menu -> Actions tab -> Delivery Pipeline appears in tabs on the right
Flows menu -> Procedures and Functions tab -> Delivery Pipeline does NOT appear in tabs on the right
Flows menu -> Notifiers tab -> Delivery Pipeline appears in tabs on the right
etc.

**Comment by pgibbs-openmake** [comment]
The Delivery Pipeline depends on which Domain is selected and is not affected by the selected view. It will always appear when a domain is selected which "contains lifecycles" regardless of menu. The only exception to this is when you're in the "Domains" menu, in which case selecting a lifecycle domain will show the tasks associated with that domain in the normal way.

**Comment by rightker** [comment]
And I should add that the page is blank, there is no actual pipeline as there is on Deploy menu -> Applications -> Click on a Domain containing Lifecycle Domains.

**Comment by rightker** [comment]
Talked with Phil, showed him where the tabs appear. They should only appear wherever there is a Domain containing Lifecycles, but they are showing up in several places where they shouldn't, such as those mentioned in the 3rd comment for this issue. He'll look into this and fix.

**Comment by pgibbs-openmake** [comment]
FIxed. Issue was domains with no sub-domains was showing the Delivery Pipeline tab. Rebuild/Retest required.

**Comment by sbtaylor15** [comment]
Fixed in 20161121_615
