### ISSUE TITLE
colors

### ISSUE THREAD

**Issue by sbtaylor15** [OpenMake-Software/ReleaseEngineer#162]
All bright colors need to be fixed on all screens.

**Comment by sbtaylor15** [comment]
All colors have been changed and verified

**Comment by rightker** [comment]
Colors in docs are referred to as Gold, Blue, and Slate.

**Comment by rightker** [comment]
Oops, to reiterate, colors in docs are referred to as Gold, Blue, and Slate
for the Planner.
