### ISSUE TITLE
Planner does not draw correctly when a release does not have a calendar entry

### ISSUE THREAD

**Issue by sbtaylor15** [OpenMake-Software/ReleaseEngineer#163]
Create a new release and add 2 applications to it.  Go to the Planner tab and you will see the release at the bottom of the timeline instead of the top.  I used applications that already had calendar entries.   Adding a calendar entry for the release fixes the issue.

**Comment by pgibbs-openmake** [comment]
Fixed. Rebuild and Retest.

**Comment by sbtaylor15** [comment]
Fix in build 20161201_628
