### ISSUE TITLE
Timeline/General Tabs are in Dispute with Time Taken to Deploy Chart on Deploy Times

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#166]
Select a Server in the Tree Structure -> Timeline tab -> Scroll down and pick out a deployment -> Click on the deployment number -> General tab -> Notice the time taken to deploy -> Click OK button to close window -> Trends tab -> Look at Time Taken to Deploy chart for same Server-> Look at deployment number along bottom of chart for the same deployment, notice the time is considerably different than that of the General tab in the Timeline tab.

In the installation on http://192.168.3.105, deploy #162 shows 15 seconds when the Timeline shows 3. #166 shows 10 seconds when Timeline shows 2.

**Comment by pgibbs-openmake** [comment]
The server trend graph shows the time taken to deploy to a particular server. The deployment log "general" tab shows the total time for the deployment including all steps - including the steps that did not target that server. For example, if the deployment has a "notify" step at the end, the deployment log will show a total time including the time taken to send the notification. The server trends tab will show the time taken to deploy the files only to that server. This number is likely to be lower.

**Comment by rightker** [comment]
Thanks for that explanation, closing this issue.
