### ISSUE TITLE
No way to move Infrastructure Component, Action, Proc since scrolling doesn't work

### ISSUE THREAD

**Issue by sbtaylor15** [OpenMake-Software/ReleaseEngineer#167]
Drag and drop not working since scrolling in tree doesn't work.  The best solution maybe to have a Move option on the Component that moves the component and the related Actions and Procs in one go.

**Comment by pgibbs-openmake** [comment]
Scrolling in tree works for me in Firefox and Safari. What Browser are you using?

**Comment by pgibbs-openmake** [comment]
To make drag-and-drop easier, the tree view now scrolls automatically when dragging an object and the mouse enters either the top or bottom of the div containing the tree view.

**Comment by pgibbs-openmake** [comment]
Assigned to Steve for rebuild and test.

**Comment by rightker** [comment]
Tested in Chrome. Works. Closing this issue.
