### ISSUE TITLE
Change Request Datasource Appears in General Tab of Release

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#171]
There is a Change Request Datasource field in the General Tab for Releases. This shouldn't be there.

**Comment by pgibbs-openmake** [comment]
Fixed. Rebuild and retest required.

**Comment by pgibbs-openmake** [comment]
Assigned to Kirk for retest

**Comment by rightker** [comment]
Fixed, closing this issue..
