### ISSUE TITLE
Appendable Field Appears in List in Properties Tab for Datasources but not in Edit Window

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#172]
Connections -> Data Sources -> Click on a Data Source in the tree structure -> Properties tab -> Notice there is a field called Appendable -> Click on Pencil Icon to bring up window, notice the Appendable field is missing. This is true for all Data Source types.

**Comment by pgibbs-openmake** [comment]
All Property values are rendered the same way regardless of the object to which they are attached. Appendable is a valid flag for some fields within a Repository Property (for example). The Appendable checkbox appears or disappears depending on the Property selected when adding the new property.

There is no "appendable" property for a data source but there might be in future.

I suspect we're best leaving this "as is" unless there is a very strong reason for changing it.

**Comment by rightker** [comment]
Sounds good, let's not go fixing things that don't really need fixing. Closing this issue.
