### ISSUE TITLE
Date shows 12/31/1969 for all Builds

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#173]
Data Center menu -> Build Engines tab -> Select a Build Engine in the tree structure -> click plus sign (+) to see Build Jobs -> select a Build Job -> Builds tab -> click on the Build Number link to see window -> General tab -> Date/Time is 12/31/1969

**Comment by pgibbs-openmake** [comment]
This would happen if you clicked on a build that had not been "notified" to Release Engineer (so it wasn't in its build history). Modified this to pick up the build time from Jenkins rather than Release Engineer (as it does for build duration anyway).

**Comment by pgibbs-openmake** [comment]
Assigned back to Kirk for rebuild and retest.

**Comment by rightker** [comment]
Works great, closing this issue.
