### ISSUE TITLE
delete command doesn't delete a 0 length file

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#182]
The following DMScript example produces a log that says it removed the file, but the file remains in the target directory:

set filelist = ${dropzone.files};
iterate(file: $filelist) {
  if (${file.size} = 0) {
    echo "Removing file $file";
    delete(file: $file);
  }
}

Log says:
File size is
0
Removing file

**Comment by pgibbs-openmake** [comment]
"delete" removes files from the dropzone, not from any target directory. Essentially, it is used to "tidy up" dropzones before onward transmission to the target.

I presume you're looking in the target directory rather than the dropzone?

**Comment by rightker** [comment]
I'm looking in the target directory after the deployment is finished, after
first making sure the file doesn't exist in the target directory prior to
the deployment. So it's creating the file in the dropzone, reporting that
it has deleted it, but then it deploys it to the target directory.

**Comment by pgibbs-openmake** [comment]
This works fine on my Windows build. I'll have to set it up under Linux and see if it's an issue with Linux builds.

**Comment by pgibbs-openmake** [comment]
Looks like this was down to passing $file and not ${file.dzpath} to the delete function. I may look at allowing a file object to be passed but in the meantime, can we close?

**Comment by rightker** [comment]
It was a coding error. Here is the correct example code which was placed into the DMScript docs:

set filelist = ${dropzone.files};
iterate(file: $filelist) {
  echo "File size is ";
  echo ${file.size};
  if (${file.size} = 0) {
    echo "Removing file ${file.dzpath}";
    delete(file: ${file.dzpath});
  }
}
