### ISSUE TITLE
random doesn't work

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#185]
random function generates the same number over and over on each server on a multiple server deployment. 10 for one server, 50 on another in the example PreAction script I tried on a Component, for multiple deployments.

**Comment by pgibbs-openmake** [comment]
The random number generator is seeded once for the whole system so each parallel thread is getting the same sequence. Solution is to seed the random generator with the thread id when each thread is created.

**Comment by rightker** [comment]
Works as per Phil's fix, closing this issue.
