### ISSUE TITLE
Dragging & Dropping Servers between Environments should display a red 'x'

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#21]
Dragging and dropping Servers between Environments in the tree structure is not allowed and should display a red 'x' but instead temporarily displays a green check mark followed by a small window with "Not yet implemented" err msg.

**Comment by pgibbs-openmake** [comment]
Fixed, requires a rebuild.

Phil Gibbs

Vice President Engineering / OpenMake Software <http://www.openmakesoftware.com/> / t. +44 (0)113 366 2015 / m. +44 (0)7713 731128
Follow us on: Blog <http://www.openmakesoftware.com/insights/> / Twitter  <http://www.twitter.com/openmake>/ Facebook <https://www.facebook.com/pages/OpenMake-Software/478045172208305> / LinkedIn <http://uk.linkedin.com/in/philgibbstrinem> / YouTube <https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ> /  <https://plus.google.com/114739548678948537118/posts>Google <https://plus.google.com/b/114739548678948537118/114739548678948537118/post>+ / Dynamic DevOps Suite Video <https://www.youtube.com/watch?v=GX36uELDK0I>
Winners of the Jolt Award in Change and Configuration Management

**Comment by rightker** [comment]
Tested in Build 345. Passed. Closing this bug.
