### ISSUE TITLE
Deployed Components Tab Disappears for Applications 

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#23]
Click on an Application in the tree structure -> Click on the Deployed Components tab, notice it disappears. Click on a different Application in the tree structure, notice it sometimes appears with the Deployed Components tab selected. Click back and forth between Applications in the tree structure and notice the Deployed Components tab sometimes stays selected and sometimes not. When it is selected, click on a different tab, then back on the Deployed Components tab, notice it always disappears.

**Comment by pgibbs-openmake** [comment]
There is no “Deployed Components” tab for an Application. This is a tab that is associated with Servers and shows which component versions have been deployed to the selected server.

It may be that moving from a server to an application is leaving the Deployed Components tab present. However, I have been unable to reproduce this in Chrome, IE, Firefox or Safari. Can you confirm browser version?


Phil Gibbs

Vice President Engineering / OpenMake Software <http://www.openmakesoftware.com/> / t. +44 (0)113 366 2015 / m. +44 (0)7713 731128
Follow us on: Blog <http://www.openmakesoftware.com/insights/> / Twitter  <http://www.twitter.com/openmake>/ Facebook <https://www.facebook.com/pages/OpenMake-Software/478045172208305> / LinkedIn <http://uk.linkedin.com/in/philgibbstrinem> / YouTube <https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ> /  <https://plus.google.com/114739548678948537118/posts>Google <https://plus.google.com/b/114739548678948537118/114739548678948537118/post>+ / Dynamic DevOps Suite Video <https://www.youtube.com/watch?v=GX36uELDK0I>
Winners of the Jolt Award in Change and Configuration Management

**Comment by rightker** [comment]
Downloaded and installed the latest version of Chrome, works now. Closing this issue.
