### ISSUE TITLE
Breadcrumbs don't work properly with large lists in the tree structure

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#24]
If a large list of objects is in the tree structure that go below the visible part of the list, objects that have been previously selected from below and appear as breadcrumbs aren't navigated back to when clicking on the breadcrumb. It seems that sometimes the tabs for the selected object appear and sometimes not, but the list is never scrolled up so that the object in the tree structure is shown.

**Comment by pgibbs-openmake** [comment]
There is nothing designed to scroll the tree view so that the selected node is visible. Presumably the main panel changes to the selected item though? Can you confirm?

**Comment by rightker** [comment]
It didn't before but it seems OK now. I'm thinking there's some combination
that keeps that from happening. I'll jump on it some more.

On Wed, Nov 11, 2015 at 5:29 PM, pgibbs-openmake <notifications@github.com>
wrote:

> There is nothing designed to scroll the tree view so that the selected
> node is visible. Presumably the main panel changes to the selected item
> though? Can you confirm?
>
> Sent from my iPad
>
> > On 11 Nov 2015, at 21:44, rightker <notifications@github.com> wrote:
> >
> > If a large list of objects is in the tree structure that go below the
> visible part of the list, objects that have been previously selected from
> below and appear as breadcrumbs aren't navigated back to when clicking on
> the breadcrumb. It seems that sometimes the tabs for the selected object
> appear and sometimes not, but the list is never scrolled up so that the
> object in the tree structure is shown.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenMake-Software/ReleaseEngineer/issues/24#issuecomment-155942724>
> .
>



-- 
Kirk Righter


I don't wanna go out and play. There's bees and sharp sticks outside!

**Comment by rightker** [comment]
Tested again after upgrading Google Chrome. Works fine now. I think either the newer version of the browser helped, but most likely I was impatient with redraw times. Closing this issue.
