### ISSUE TITLE
Getting Blank Log Tab on Timeline Windows

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#25]
After running a deployment, click on the Application in the tree structure -> Timeline tab -> Click on the deployment number in the list -> Log tab, notice (sometimes) that the page is blank. There is no obvious pattern to this. There are lines for the log output in the dm_deploymentlog table in PostGreSQL.

**Comment by sbtaylor15** [comment]
This will happen when dmtransfer crashes and nothing is recorded
