### ISSUE TITLE
Adding Component to App and Then Going to the Component Hangs

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#27]
Deploy menu -> Applications tab -> Assigned Components tab -> Drag and Drop a Component from the list on the right into the main area -> Right click on the newly added Component and select "Go to this Component", notice it hangs indefinitely with the "Loading..." message. Redraw to get it to show correctly. If you redraw before right clicking and selecting "Go to this Component" it behaves correctly.

**Comment by pgibbs-openmake** [comment]
Fixed. New build required.

Phil Gibbs

Vice President Engineering / OpenMake Software <http://www.openmakesoftware.com/> / t. +44 (0)113 366 2015 / m. +44 (0)7713 731128
Follow us on: Blog <http://www.openmakesoftware.com/insights/> / Twitter  <http://www.twitter.com/openmake>/ Facebook <https://www.facebook.com/pages/OpenMake-Software/478045172208305> / LinkedIn <http://uk.linkedin.com/in/philgibbstrinem> / YouTube <https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ> /  <https://plus.google.com/114739548678948537118/posts>Google <https://plus.google.com/b/114739548678948537118/114739548678948537118/post>+ / Dynamic DevOps Suite Video <https://www.youtube.com/watch?v=GX36uELDK0I>
Winners of the Jolt Award in Change and Configuration Management

**Comment by rightker** [comment]
Tested in Build 351(3), works, closing this issue.
