### ISSUE TITLE
Creating New Proc or Func Takes on Parameters from Last Deleted one

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#29]
Build 351: Create a new Procedure or Function with parameters -> Move the parameters to the Command Line -> Delete the Proc or Func from the tree structure ->  Create another Procedure or Function -> Notice the parameters from the one just deleted are on the Command Line of the new Func or Proc

**Comment by pgibbs-openmake** [comment]
Fixed. New build required.

Phil Gibbs

Vice President Engineering / OpenMake Software <http://www.openmakesoftware.com/> / t. +44 (0)113 366 2015 / m. +44 (0)7713 731128
Follow us on: Blog <http://www.openmakesoftware.com/insights/> / Twitter  <http://www.twitter.com/openmake>/ Facebook <https://www.facebook.com/pages/OpenMake-Software/478045172208305> / LinkedIn <http://uk.linkedin.com/in/philgibbstrinem> / YouTube <https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ> /  <https://plus.google.com/114739548678948537118/posts>Google <https://plus.google.com/b/114739548678948537118/114739548678948537118/post>+ / Dynamic DevOps Suite Video <https://www.youtube.com/watch?v=GX36uELDK0I>
Winners of the Jolt Award in Change and Configuration Management

**Comment by sbtaylor15** [comment]
Retest

**Comment by sbtaylor15** [comment]
Passed in 4/14 build
