### ISSUE TITLE
fileserver Repository's filepath parameter doesn't interpret UNC names correctly

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#3]
When a Domain’s Engine field references a non-local server in order to use its Engine for a deployent, any filesystem type Repositories by default will attempt to reference files on the non-local server, and not the localhost server. It is more typical to have filesystem Repositories on the localhost. Go to the Connections menu -> Repositories tab in the tree structure -> select a filesystem Repository in the tree structure (or create a new one) ->  Properties tab. The filepath parameter contains the path to the files that make up a filesystem Repository, and can be used to tell the Engine on the non-local host to point back to the localhost. An example would be c:\test\myfiles on the server with the non-fully qualified server name ‘retest’. A UNC reference could to be placed into this field, which in this example would be \\retest\c$\test\myfiles. Currently there is a bug with Release Engineer Build 339 which prevents this. The log shows it being interpreted as:

Runtime error: Base directory '\\retest\c\\retest\c$\test\100MB' of repository 'TDE_Repo2' does not exist.

The prefix \\retest\c is added for some unknown reason. A workaround is to use a mapped drive with a letter such as x to reference c:\test\myfiles so that the value for filepath would be x:\

**Comment by sbtaylor15** [comment]
retest UNC names in repo base dir.  path names in component items are appended

**Comment by sbtaylor15** [comment]
UNC names will not be supported.  The UNC path should be mapped to a drive or NFS mount to make them appear as a local filesystem.
