### ISSUE TITLE
Reserved Event in Calendar Doesn't Show App After Time has Passed

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#30]
Create a Reserved Event in the Calendar for a given Environment for a given Application. After the reserved time has passed, click on the Reserved Event, and select View This Event. Notice there is no Application selected. Sometimes doing the same thing to a Reserved Event that is set in the future does the same thing (select Modify This Event), but there is no pattern to it.

**Comment by pgibbs-openmake** [comment]
Fixed - requires retesting

**Comment by rightker** [comment]
Failed testing. Same behaviour as before.

**Comment by sbtaylor15** [comment]
Retest, with current build

**Comment by rightker** [comment]
Works correctly, closing this issue.
