### ISSUE TITLE
New Notifier Template has User Names by Default

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#31]
Flows menu -> Notifiers tab -> Right click on a Notifier in the tree structure -> New Notifier Template for this Notifier -> Fill in Name and Summary fields, click OK -> Recipients tab, notice that there are Users already in the list.

**Comment by pgibbs-openmake** [comment]
Unable to reproduce.

Phil Gibbs

Vice President Engineering / OpenMake Software <http://www.openmakesoftware.com/> / t. +44 (0)113 366 2015 / m. +44 (0)7713 731128
Follow us on: Blog <http://www.openmakesoftware.com/insights/> / Twitter  <http://www.twitter.com/openmake>/ Facebook <https://www.facebook.com/pages/OpenMake-Software/478045172208305> / LinkedIn <http://uk.linkedin.com/in/philgibbstrinem> / YouTube <https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ> /  <https://plus.google.com/114739548678948537118/posts>Google <https://plus.google.com/b/114739548678948537118/114739548678948537118/post>+ / Dynamic DevOps Suite Video <https://www.youtube.com/watch?v=GX36uELDK0I>
Winners of the Jolt Award in Change and Configuration Management

**Comment by sbtaylor15** [comment]
retest, templates have been reworked

**Comment by rightker** [comment]
Works as expected, closing this issue.
