### ISSUE TITLE
Attempting to Create a Domain Causes "Loading..." Error

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#34]
Attempting to Create a Domain Causes "Loading..." Error. Refresh shows the Domain in the tree structure, but clicking on the General tab for the new Domain also shows the "Loading..." error.

**Comment by pgibbs-openmake** [comment]
Cannot reproduce on development build. Tested in Firefox and Safari. Can you retest with console open and see if anything’s reported?

Phil Gibbs

Vice President Engineering / OpenMake Software <http://www.openmakesoftware.com/> / t. +44 (0)113 366 2015 / m. +44 (0)7713 731128
Follow us on: Blog <http://www.openmakesoftware.com/insights/> / Twitter  <http://www.twitter.com/openmake>/ Facebook <https://www.facebook.com/pages/OpenMake-Software/478045172208305> / LinkedIn <http://uk.linkedin.com/in/philgibbstrinem> / YouTube <https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ> /  <https://plus.google.com/114739548678948537118/posts>Google <https://plus.google.com/b/114739548678948537118/114739548678948537118/post>+ / Dynamic DevOps Suite Video <https://www.youtube.com/watch?v=GX36uELDK0I>
Winners of the Jolt Award in Change and Configuration Management

**Comment by rightker** [comment]
Reproduced and sent error to Phil G. via Skype. Fixed, tested, and placed into Git for next Build. Closing this issue.
