### ISSUE TITLE
OK Button Doesn't Work for Testing Notifier

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#37]
Right click on a Notifier in the tree structure -> select "Send a Test Message using this Notifier" ->click OK button, notice it doesn't cause the window to go away, so nothing happens.

**Comment by pgibbs-openmake** [comment]
That's because it's not implemented yet! Will be for the 7.6 release...

**Comment by rightker** [comment]
Curses! Foiled again!

(Don't bother reading this if you're already asleep)

On Tue, Dec 15, 2015 at 3:28 PM, pgibbs-openmake <notifications@github.com>
wrote:

> That's because it's not implemented yet! Will be for the 7.6 release...
>
> Sent from my iPhone
>
> > On 15 Dec 2015, at 21:08, rightker <notifications@github.com> wrote:
> >
> > Assigned #37 to @pgibbs-openmake.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenMake-Software/ReleaseEngineer/issues/37#issuecomment-164912879>
> .
>



-- 
Kirk Righter


I don't wanna go out and play. There's bees and sharp sticks outside!
