### ISSUE TITLE
Failed Notification Field for Tasks Doesn't Accept Entries

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#39]
Domains menu -> Domains tab -> Tasks tab -> Click on a Domain in the tree structure -> Tasks tab -> Click on an existing Task or create a new one -> Click Pencil icon to edit the Task -> Select a Notification Template from the Success Notification Template list -> Select a Notification Template from the Failure Notification Template list -> Click OK, notice the Successful Notification Template field has the Failed Template, and the Failed Notification Template is blank.

**Comment by sbtaylor15** [comment]
Retest.

**Comment by rightker** [comment]
There are no Notification templates available, no fields on the dialog (?)

**Comment by pgibbs-openmake** [comment]
Not sure why no notification templates were available (depends on which domain you were in I guess) but issue is solved now. Rebuild and retest required.

**Comment by rightker** [comment]
Works now, closing this issue.
