### ISSUE TITLE
Can't have a Proc or Func with same name as Action

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#41]
If an Action is run that contains a Procedure or Function with the same name as the Action, an error is thrown as a result of an infinite loop that uses up stack space. Example log output:

INFO: Deployed File simpleDOS.bat -> cramer:c:\temp/simpleDOS.bat
Exception at line 0: push failed: scope stack size exceeded
Stacktrace:
    action loadjava
    action loadjava at fragment 1
    action loadjava at fragment 1
    action loadjava at fragment 1
    etc...
    dropzone 1
    deploy

**Comment by pgibbs-openmake** [comment]
There are new fixes to prevent an object being created with the same name as an existing object in the same domain. This means that actions/procedures/functions can no longer have the same name as each other provided they are within the same domain.

Phil Gibbs

Vice President Engineering / OpenMake Software <http://www.openmakesoftware.com/> / t. +44 (0)113 366 2015 / m. +44 (0)7713 731128
Follow us on: Blog <http://www.openmakesoftware.com/insights/> / Twitter  <http://www.twitter.com/openmake>/ Facebook <https://www.facebook.com/pages/OpenMake-Software/478045172208305> / LinkedIn <http://uk.linkedin.com/in/philgibbstrinem> / YouTube <https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ> /  <https://plus.google.com/114739548678948537118/posts>Google <https://plus.google.com/b/114739548678948537118/114739548678948537118/post>+ / Dynamic DevOps Suite Video <https://www.youtube.com/watch?v=GX36uELDK0I>
Winners of the Jolt Award in Change and Configuration Management

**Comment by rightker** [comment]
Tested, works. Closing this issue.
