### ISSUE TITLE
Need to delete 4 Procedures

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#42]
Start Application, Stop Application, Start Server, and Stop Server need to be removed from the list on the right side of the Actions Workflow editor, as the WebSphereDeploy Procedure already contains all of these capabilities.

**Comment by sbtaylor15** [comment]
This was put into build build 412.  Please confirm.

**Comment by rightker** [comment]
Can't see any of them in Build 415, closing this issue.
