### ISSUE TITLE
Newly Created Procs and Funcs have a Body tab when created in Demo Domain

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#43]
Create a new Procedure or Function in the Demo Domain -> Click on the newly created Func or Proc in the Tree Structure, Notice the tabs from left to right are Body, Args, Access, General. Click on a Func or Proc in Global or any other Domain, either an older one or a newly created one, notice the tabs are Args, Access, General. Clicking back and forth into and out of Demo doesn't redraw it correctly, redrawing the web page or logging out and back in doesn't do away with the Body tab.

**Comment by pgibbs-openmake** [comment]
Cannot reproduce.

Body tab only exists for DMScript functions/procedures. If the function or procedure is of type “external” then body will not be shown.

Can you confirm what type each function/procedure is? In other words, is “body” ever appearing for an external script (either local or remote) or is no body appearing for DMScript based functions/procedures?

Phil Gibbs

Vice President Engineering / OpenMake Software <http://www.openmakesoftware.com/> / t. +44 (0)113 366 2015 / m. +44 (0)7713 731128
Follow us on: Blog <http://www.openmakesoftware.com/insights/> / Twitter  <http://www.twitter.com/openmake>/ Facebook <https://www.facebook.com/pages/OpenMake-Software/478045172208305> / LinkedIn <http://uk.linkedin.com/in/philgibbstrinem> / YouTube <https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ> /  <https://plus.google.com/114739548678948537118/posts>Google <https://plus.google.com/b/114739548678948537118/114739548678948537118/post>+ / Dynamic DevOps Suite Video <https://www.youtube.com/watch?v=GX36uELDK0I>
Winners of the Jolt Award in Change and Configuration Management

**Comment by rightker** [comment]
It's only when it's stored in the database, as it should be. Duh. Closing this issues.
