### ISSUE TITLE
Build 387: Newly created Component Items don't appear until redraw

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#44]
Deploy menu -> Components tab -> Click on a Component in the tree structure -> Component Items tab -> Right click on Component Items area and select Create New Component Item, nothing seems to happen, but a redraw shows the Component Item in the upper left part of the area, if you scroll to see it. It is not connected to any other Component Items.

**Comment by sbtaylor15** [comment]
Retest

**Comment by rightker** [comment]
Works, closing this issue.
