### ISSUE TITLE
New Component with Database Type Creates Only One Component Item

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#45]
Build 387: Deploy menu -> Components tab -> Right Click on a Domain in the tree structure -> New Component for this Domain -> Fill out General info in the window, choose a database type as the Component Type -> Click OK -> Component Items tab, notice there is only on Component Item and its labeled 'Roll Forward'. There should be two Component Items.

**Comment by pgibbs-openmake** [comment]
This works for me. Can you check that the type you’re selecting has “Database Rollforward/Rollback” set? To do this:

Domains Menu -> Component & Server Types tab -> click on the type. Ensure that “Database Roll-forward/Rollback” is set to “Yes”.

Phil Gibbs

Vice President Engineering / OpenMake Software <http://www.openmakesoftware.com/> / t. +44 (0)113 366 2015 / m. +44 (0)7713 731128
Follow us on: Blog <http://www.openmakesoftware.com/insights/> / Twitter  <http://www.twitter.com/openmake>/ Facebook <https://www.facebook.com/pages/OpenMake-Software/478045172208305> / LinkedIn <http://uk.linkedin.com/in/philgibbstrinem> / YouTube <https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ> /  <https://plus.google.com/114739548678948537118/posts>Google <https://plus.google.com/b/114739548678948537118/114739548678948537118/post>+ / Dynamic DevOps Suite Video <https://www.youtube.com/watch?v=GX36uELDK0I>
Winners of the Jolt Award in Change and Configuration Management

**Comment by rightker** [comment]
Yes, it does have the Rollback/Forward set to 'Yes'.

**Comment by sbtaylor15** [comment]
Retest

**Comment by rightker** [comment]
Works, closing this issue.
