### ISSUE TITLE
Need a Check/Error Msg for Combination of Base Directories

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#46]
The Base Directory for a Component can either be absolute, i.e. 'C:\main' for Windows or '/main' for Linux/Unix, etc., in which case it replaces the Base Directory for the Server. If the Component's Base Directory is relative, i.e. 'SomeFiles\SomeMoreFiles', then it is appended to the Server's Base Directory, i.e. 'C:\main\SomeFiles\SomeMoreFiles'.
If the Component Item's Target Directory has a value, it is always appended to the end of whatever value has been created from the Base Directories of the Server and Component.

Is a preflight check needed for each Server to make certain that the combinations are correct before Deploying?

**Comment by pgibbs-openmake** [comment]
That's almost impossible to do for several reasons. Firstly, you don't target a server you target an environment. Secondly you would need to supply both the app and the target environment to match the components with the servers. Thirdly, the paths may include variables which are only expandable at deploy time.

**Comment by rightker** [comment]
Excellent. Closing this issue.
