### ISSUE TITLE
Fields in Credential's General tab are missing, mislabeled 

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#5]
Build 339: Connections menu -> Credentials tab -> Click on a Credential in the tree structure or create one -> General tab, notice that the User Name is starred out, and there is a field named Filename which is always blank.

**Comment by sbtaylor15** [comment]
The credential is encrypted in the DB so we do not unencrypt it for display, instead leave it blank.  We can use something else than blank fields.  Any suggestions?

**Comment by rightker** [comment]
Shouldn't we show the username as it is and password as asterisks? This is standard as far as I know. Do we encrypt the username in the database?

**Comment by pgibbs-openmake** [comment]
Both are encrypted. We can decrypt username for display but that sort of makes encrypting the username in the first place rather pointless.

I'd be inclined to show asterisks for both.

**Comment by rightker** [comment]
Sounds good. I'm in.

**Comment by sbtaylor15** [comment]
Retest

**Comment by sbtaylor15** [comment]
Encrypted username is displayed un-encrypted format. Encrypted password shows a blank.  Re-open if  ***** is needed for pw.
