### ISSUE TITLE
Clicking on Categories in Tree Structure and Then Any Tab, Make Tabs Disappear

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#51]
Clicking on any Category in the tree structure, and then any tab on the right, makes all of the tabs disappear. Are there supposed to be any tabs on the right side after choosing a Category?

**Comment by sbtaylor15** [comment]
No, it should be blank for Categories.

**Comment by rightker** [comment]
Build 415: Fixed, closing this issue.
