### ISSUE TITLE
Component With 2 Items With Custom Action, Some Version Fields Don't Reappear

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#54]
Deploy menu -> Components tab -> Right click on a Domain -> New Component Base Version in this Domain -> New Component Base Version window appears -> Select DB2 as the Component Type, notice there are new fields which include pattern, recursive, and version, one set each for Rollforward and Rollback. -> Select a Custom Action, notice all of the pattern, recursive, and version fields disappear. Choose the blank line for the Custom Action, doing away with it altogether. Notice the pattern, recursive, and version fields come back, but only one set of them, and above the Rollforward and Rollback fields.

**Comment by pgibbs-openmake** [comment]
Working now. Retest required.

**Comment by sbtaylor15** [comment]
Passed in build 4/14
