### ISSUE TITLE
Can't Copy and Paste a Procedure/Function

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#55]
Copying and pasting a Procedure or a Function from one Domain into another in the tree structure doesn't work. The Copy Procedure appears in the right click menu, and the Paste Procedure appears as well, but nothing happens.

**Comment by pgibbs-openmake** [comment]
Fixed. Copying a procedure/function worked but did not copy category so newly pasted object was not visible in tree view. This has been sorted (New build reqd)
Phil Gibbs

Vice President Engineering / OpenMake Software <http://www.openmakesoftware.com/> / t. +44 (0)113 366 2015 / m. +44 (0)7713 731128
Follow us on: Blog <http://www.openmakesoftware.com/insights/> / Twitter  <http://www.twitter.com/openmake>/ Facebook <https://www.facebook.com/pages/OpenMake-Software/478045172208305> / LinkedIn <http://uk.linkedin.com/in/philgibbstrinem> / YouTube <https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ> /  <https://plus.google.com/114739548678948537118/posts>Google <https://plus.google.com/b/114739548678948537118/114739548678948537118/post>+ / Dynamic DevOps Suite Video <https://www.youtube.com/watch?v=GX36uELDK0I>
Winners of the Jolt Award in Change and Configuration Management

**Comment by rightker** [comment]
Doesn't redraw the Procedure/function automatically, have to redraw, and then it shows in both the correct Category and in the General Category.

**Comment by sbtaylor15** [comment]
Retest, takes category into account

**Comment by rightker** [comment]
Doesn't work at all. Nothing gets pasted into the target Domain.

**Comment by pgibbs-openmake** [comment]
Problem was caused by the function/procedure not getting a matching fragment created during the paste process - due to an earlier fix the tree view now takes the function/procedure from its fragment category. Should now work - build and test required.

**Comment by sbtaylor15** [comment]
Passed testing in build 4/13
