### ISSUE TITLE
Deployed Components Tab Remains After Selecting a Server in the Tree on Chrome

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#56]
End Points menu -> Environments tab -> Servers tab -> Click on a Server in the tree structure, notice there are 6 tabs on the right including Deployed Components -> Click on any other menu -> Click on any tab and/or object, notice the Deployed Components remains as a tab on the right side -> Click on the Deployed Components tab and notice all the tabs disappear. This only happens for Servers within Environments, the same behavior doesn't exist for Servers under the Servers tab. This only happens on Chrome.

**Comment by pgibbs-openmake** [comment]
Confirmed bug on Chrome. The reason it happens is that the tab logic is flawed. When switching between tree views, the old tabs are cleared based on the previously selected tree. When selecting a “server” under the environments tab, the tab list is for “servers”, not “environments” so the logic clears the tabs for “environments” leaving the additional server tabs (Deployed Components and Status) displayed. It is not clear why this bug only manifests itself on Chrome.

I will need to change the tab logic.


Phil Gibbs

Vice President Engineering / OpenMake Software <http://www.openmakesoftware.com/> / t. +44 (0)113 366 2015 / m. +44 (0)7713 731128
Follow us on: Blog <http://www.openmakesoftware.com/insights/> / Twitter  <http://www.twitter.com/openmake>/ Facebook <https://www.facebook.com/pages/OpenMake-Software/478045172208305> / LinkedIn <http://uk.linkedin.com/in/philgibbstrinem> / YouTube <https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ> /  <https://plus.google.com/114739548678948537118/posts>Google <https://plus.google.com/b/114739548678948537118/114739548678948537118/post>+ / Dynamic DevOps Suite Video <https://www.youtube.com/watch?v=GX36uELDK0I>
Winners of the Jolt Award in Change and Configuration Management

**Comment by pgibbs-openmake** [comment]
Fixed and submitted to git. When clearing environment tabs, code now also clears server tabs (in case server tabs were displayed).

Phil Gibbs

Vice President Engineering / OpenMake Software <http://www.openmakesoftware.com/> / t. +44 (0)113 366 2015 / m. +44 (0)7713 731128
Follow us on: Blog <http://www.openmakesoftware.com/insights/> / Twitter  <http://www.twitter.com/openmake>/ Facebook <https://www.facebook.com/pages/OpenMake-Software/478045172208305> / LinkedIn <http://uk.linkedin.com/in/philgibbstrinem> / YouTube <https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ> /  <https://plus.google.com/114739548678948537118/posts>Google <https://plus.google.com/b/114739548678948537118/114739548678948537118/post>+ / Dynamic DevOps Suite Video <https://www.youtube.com/watch?v=GX36uELDK0I>
Winners of the Jolt Award in Change and Configuration Management

**Comment by rightker** [comment]
Build 423: Works correctly. Closing this issue.
