### ISSUE TITLE
Install RPM Doesn't Start postgresql 

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#57]
The RPM for Release Engineer for Redhat 7 Linux installs the postgresql process, but doesn't start it. It has to be started, and then the webadmin process has to be restarted. Otherwise, the web page doesn't function and a 503 message appears when attempting to access it.
The initial install on a clean server starts correctly with all 3 processes (re-engine, re-webadmin, and postgresql) and allows the webpage to function, but when restarting the server again it fails.
When this fails, need to:

su
systemctl start postgresql
systemctl restart re-webadmin

**Comment by sbtaylor15** [comment]
Fixed and passed testing
