### ISSUE TITLE
Application Versions Don't Show in the Same Domain as the Application Base Version

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#58]
Deploy menu -> Applications tab -> Right click on an Application in the tree structure -> Create Version (the Create Version Task should have the same Domain for the "Create Version in Domain" field as the Application Base Version). Notice the Application Version doesn't show in the tree structure within the same Domain as the Application Base Version. It should. However, if another Create Task Version is used, and it has a different Domain for the "Create Version in Domain" field, it will show in the tree in that Domain.

**Comment by pgibbs-openmake** [comment]
Modification to the APPLICATION/APPVERSION tree logic is now in git.

App VERSIONS are shown as children of the BASE application ONLY IF they are in the same domain as the BASE application. The old logic only did this if the base and versions were in a domain BELOW a domain marked as being a lifecycle. If the BASE and VERSION were in the same domain but the domain was marked as a lifecycle then no children would be shown.
    
The new logic works consistently and ignores the "lifecycle" flag of the domain. So if the BASE is in the parent and the child versions move through the lifecycle domains, there is no change to the functionality. Only if the child exists in the same domain as the BASE is it now visible as a child of the BASE.

Phil Gibbs

Vice President Engineering / OpenMake Software <http://www.openmakesoftware.com/> / t. +44 (0)113 366 2015 / m. +44 (0)7713 731128
Follow us on: Blog <http://www.openmakesoftware.com/insights/> / Twitter  <http://www.twitter.com/openmake>/ Facebook <https://www.facebook.com/pages/OpenMake-Software/478045172208305> / LinkedIn <http://uk.linkedin.com/in/philgibbstrinem> / YouTube <https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ> /  <https://plus.google.com/114739548678948537118/posts>Google <https://plus.google.com/b/114739548678948537118/114739548678948537118/post>+ / Dynamic DevOps Suite Video <https://www.youtube.com/watch?v=GX36uELDK0I>
Winners of the Jolt Award in Change and Configuration Management

**Comment by sbtaylor15** [comment]
Working as designed.
