### ISSUE TITLE
"Goto this Component" doesn't work

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#65]
Build 425: Right click on a Component in the Ass.igned Components tab for an Application and select "Goto this Component". It changes to the Components tab, but doesn't select the Component in the tree structure or display the Component in any way.

**Comment by pgibbs-openmake** [comment]
Fixed and commited to git. Problem was when a new component version was created, it was not copying the category. 

Phil Gibbs

Vice President Engineering / OpenMake Software <http://www.openmakesoftware.com/> / t. +44 (0)113 366 2015 / m. +44 (0)7713 731128
Follow us on: Blog <http://www.openmakesoftware.com/insights/> / Twitter  <http://www.twitter.com/openmake>/ Facebook <https://www.facebook.com/pages/OpenMake-Software/478045172208305> / LinkedIn <http://uk.linkedin.com/in/philgibbstrinem> / YouTube <https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ> /  <https://plus.google.com/114739548678948537118/posts>Google <https://plus.google.com/b/114739548678948537118/114739548678948537118/post>+ / Dynamic DevOps Suite Video <https://www.youtube.com/watch?v=GX36uELDK0I>
Winners of the Jolt Award in Change and Configuration Management

**Comment by rightker** [comment]
Fixed in Build 426. Closing this issue.
