### ISSUE TITLE
Strange Behaviour with Moving Applications

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#68]
An Application Base was named testApp423 and was later renamed testApp426, after creating several Application Versions from the original. There are no longer any Application Versions that belong to this Base Application (can't remember if I deleted them after all the testing that has been performed) in the tree, but in the Versions tab, testApp423;1 shows . Whenever the Application is moved from it's original Domain (test426) to another one (newTest) it shows up in the tree with an Application Version with the original name and a prefix of ;1 (testApp423;1), and there are 2 others that suddenly appear in the original Domain (testApp423;2 and testApp423;3). When it's moved back to the original Domain, the Versions all disappear again.

**Comment by sbtaylor15** [comment]
Retest move/copy has been reworked

**Comment by rightker** [comment]
Unable to move an Application from one Domain to another. All other objects can be moved. Is this OK? It would nullify this test.

**Comment by pgibbs-openmake** [comment]
That's correct. Moving of Applications is controlled by the "Move" task. Moves can only be completed should any associated approval task for the target domain have been run. This is working as designed.

However, this has ALWAYS been the case - it has never been possible to move an application with drag/drop. So I assume the original test was done with running a "Move" task?
