### ISSUE TITLE
Limit to Number of Lines Shown in Timeline

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#69]
The Timeline tab for an Application only shows a certain number of lines (around 100), along with the "Click to see earlier items" link at the bottom. Clicking on the link doesn't show any more lines. Is this by design?

**Comment by pgibbs-openmake** [comment]
Yes. It’s based on time, not number of entries.


Phil Gibbs

Vice President Engineering / OpenMake Software <http://www.openmakesoftware.com/> / t. +44 (0)113 366 2015 / m. +44 (0)7713 731128
Follow us on: Blog <http://www.openmakesoftware.com/insights/> / Twitter  <http://www.twitter.com/openmake>/ Facebook <https://www.facebook.com/pages/OpenMake-Software/478045172208305> / LinkedIn <http://uk.linkedin.com/in/philgibbstrinem> / YouTube <https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ> /  <https://plus.google.com/114739548678948537118/posts>Google <https://plus.google.com/b/114739548678948537118/114739548678948537118/post>+ / Dynamic DevOps Suite Video <https://www.youtube.com/watch?v=GX36uELDK0I>
Winners of the Jolt Award in Change and Configuration Management

**Comment by rightker** [comment]
The one I'm looking at has only 7 days as the latest entry. I've been using it for testing over the last week or so, so it has a lot of entries.

**Comment by rightker** [comment]
Double checked this, I think Phil is right. Closing this issue and will reopen if necessary.
