### ISSUE TITLE
Base directory in Component  is not inherited by Component Version

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#7]
Build 339: Deploy menu -> Components tab -> Select a Component in the tree structure or create a new one (make sure that the Base Directory in the General tab contains a value) -> Versions tab -> Right click anywhere in the area below and select Create New Component Version -> Click on the new Component Version in the tree structure -> General tab, notice the Base Directory for the new Component Version is blank.

**Comment by sbtaylor15** [comment]
Retest, copy and create version cleaned up

**Comment by rightker** [comment]
Still doesn't copy the base directory.

**Comment by sbtaylor15** [comment]
Is this on a Create New Component version or copy/paste of a component version?

**Comment by pgibbs-openmake** [comment]
Should be fixed now - new build and retest required.

**Comment by sbtaylor15** [comment]
Passed testing in 4/13 build.
