### ISSUE TITLE
Unusual Behaviour When Adding a Procedure to an Action 

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#75]
Log in as Administrator -> Pick an existing Action in the tree structure under Flows menu  -> Log out and back in as someone without access to the Action. Workflow tab -> Drag a Procedure from the right side tree structure onto the Workflow area, notice the Procedure window pops up with all of the fields but only a Cancel button. There is no OK button. Hitting the Cancel button makes the window go away, but the box for the Procedure stays in the Workflow area. Right clicking on the Procedure box in the Workflow area presents no Delete option.
If the User has no access to the Procedure or Function, dragging and dropping onto the Workflow area should not be allowed.

**Comment by rightker** [comment]
The entire window is greyed out when selecting the Procedure/Function/Action that the User has no Access to, however, if the User redraws the window, everything becomes available and can be changed.

**Comment by rightker** [comment]
Build 434: The grey area does not go all the way to the top, and anything above it is active. Also, the ability to bring objects onto the grey area exists, such as the version window from the upper right corner or the right-click 'View Generated DMScript'. The window appears but its OK button is not activated so it can't be put away.

**Comment by rightker** [comment]
Tested this again, seems to work fine. Was this fixed, or is it a side effect of some other fix? ;-) Closing this issue.

**Comment by pgibbs-openmake** [comment]
Think Steve fixed this - may be worth checking with him.
