### ISSUE TITLE
'Test Connection to this Data Source' throws error

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#79]
Connections menu -> Data Sources tab -> Right click on a Data Source in the tree structure and select 'Test Connection to this Data Source', notice the error "Exception: Unrecognised datasource type 'ldap'" appears.

**Comment by sbtaylor15** [comment]
Please retest

**Comment by rightker** [comment]
I get a blank "Test Datasource Results" dialogue. Is that OK?

**Comment by pgibbs-openmake** [comment]
Cannot reproduce. Successful connection says "Connection to LDAP server ok", a failed connection (by changing port number from 389 to 390 for example) reports the connection timeout and failure.

**Comment by rightker** [comment]
I still get a blank window that pops up on the latest build (379).

**Comment by pgibbs-openmake** [comment]
Is this on Linux or Windows Server?

**Comment by rightker** [comment]
Both

**Comment by rightker** [comment]
Blank msg when Credential was missing. That's been fixed. Closing this issue.
