### ISSUE TITLE
Component Version Attributes are not inherited from latest Component Version, but by Component 

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#8]
Build 339: Deploy menu -> Components tab -> Create a new Component Base Version in the tree structure -> Click on Attributes tab -> Enter an Attribute for the new Component by clicking on the '+' button, enter the values, and click OK -> Click on Versions tab for this new Component Base Version -> Right click in the area below the tabs and select 'Create New Component Version' -> Click on the newly created Component Version in the tree structure -> Click on Attributes tab, notice the Attribute has been inherited from the Component Base Version, as expected -> Create another Attribute in the Component Version, so that the Base has one and the Version now has two Attributes -> Create another Component Version, notice that it does not inherit the newly created Attribute from the Component Version, but from the Base Version. Is this correct?

**Comment by sbtaylor15** [comment]
Retest.

**Comment by pgibbs-openmake** [comment]
Working as expected now (and has done for some time). Retest

**Comment by sbtaylor15** [comment]
I get that it is inheriting from the latest version not the base version. Is this the expected results?

**Comment by pgibbs-openmake** [comment]
That's the expected result - it should pick up the attributes from the latest version.
