### ISSUE TITLE
Can't delete a Domain

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#80]
Right click on a Domain a dn select "Delete this Domain". The Domain disappears, but then shows up after redraw. Sometimes a sub Domain can be deleted.

**Comment by sbtaylor15** [comment]
Still and issue with 4/14 build.  Delete the demo domain.  No error message even though it has stuff still associated to the domain. Domain is deleted, but on refresh it shows back up.

**Comment by pgibbs-openmake** [comment]
FIxed rebuild and retest required. Server was reporting inability to delete domain but client was checking wrong result attribute.

**Comment by rightker** [comment]
Works fine now, closing this issue.
