### ISSUE TITLE
New Domain shows in tree as "newnode" in Linux version

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#81]
Newly created Domain shows in tree as "newnode" in Linux version (General tab shows as actual name initially). Redraw causes it to show actual name in tree.

**Comment by sbtaylor15** [comment]
What should the new node name be set to as default?

**Comment by rightker** [comment]
Still a problem.

**Comment by pgibbs-openmake** [comment]
Should be fixed. New build and retest required.

**Comment by sbtaylor15** [comment]
Passed in 4/14 build.
