### ISSUE TITLE
Credentials are getting mangled

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#82]
Create a new Credential (don't use an existing one, it might be getting broken)
Enter username/password
Enter the Credential into a Server's General tab
Go to the Server's Status tab
Hit the Test Now button, notice it doesn't connect. It pings and the name resolves, but no connection.
Go back to the Credential, notice the General tab has no contents. Redrawing doesn't help.  This is happening on both Windows and Linux.

**Comment by rightker** [comment]
After further testing it was determined that editing the Credential causes the problem.

**Comment by pgibbs-openmake** [comment]
Bug confirmed on local development machine this a.m. Editing the credential causes the username to be stored un-encrypted. This then breaks the decrypt mechanism when the credential is displayed by the credential owner.

Phil Gibbs

Vice President Engineering / OpenMake Software <http://www.openmakesoftware.com/> / t. +44 (0)113 366 2015 / m. +44 (0)7713 731128
Follow us on: Blog <http://www.openmakesoftware.com/insights/> / Twitter  <http://www.twitter.com/openmake>/ Facebook <https://www.facebook.com/pages/OpenMake-Software/478045172208305> / LinkedIn <http://uk.linkedin.com/in/philgibbstrinem> / YouTube <https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ> /  <https://plus.google.com/114739548678948537118/posts>Google <https://plus.google.com/b/114739548678948537118/114739548678948537118/post>+ / Dynamic DevOps Suite Video <https://www.youtube.com/watch?v=GX36uELDK0I>
Winners of the Jolt Award in Change and Configuration Management

**Comment by rightker** [comment]
Discovered another thing: unable to delete one of these broken Credentials. Right clicking on them in the tree structure shows nothing in the drop down list.

**Comment by rightker** [comment]
Fixed in Linux version, not in Windows. Closing this issue.
