### ISSUE TITLE
"Paste Component" appears everywhere after Copy 

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#85]
Right click on a Component and select "Copy" from the drop down list. Right click on any Domain in the tree structure and notice "Paste Component" appears.

**Comment by pgibbs-openmake** [comment]
Why is this a problem? Where do you expect the paste option to appear?

**Comment by rightker** [comment]
Not under Flows:Notifiers. Not under Connections:Repositories. I mean, any
Domain..

**Comment by pgibbs-openmake** [comment]
Oh you mean if you switch tabs? I think that happens for everything, not just components... It works though - you just need to switch back to the right tab and it'll be in the domain. May be an idea to tidy that up though.

**Comment by rightker** [comment]
So it's a feature? ;-)
