### ISSUE TITLE
sftp protocol status test does not show full error message

### ISSUE THREAD

**Issue by sbtaylor15** [OpenMake-Software/ReleaseEngineer#87]
Just shows first line.

**Comment by pgibbs-openmake** [comment]
Not clear from the error but are you referring to "Last Error" on the status tab?

If so, can you give an example of an error that has multiple lines?

**Comment by sbtaylor15** [comment]
# redhat72.gotdns.com:22 SSH-2.0-OpenSSH_6.6.1
# redhat72.gotdns.com:22 SSH-2.0-OpenSSH_6.6.1
Warning: Permanently added the RSA host key for IP address '54.174.171.99' to the list of known hosts.^M
Permission denied, please try again.^M


and we are only getting the following displayed.

# redhat72.gotdns.com:22 SSH-2.0-OpenSSH_6.6.1

**Comment by sbtaylor15** [comment]
Passed in 4/22 build
