### ISSUE TITLE
Cannot specify Repository for DMScript

### ISSUE THREAD

**Issue by pgibbs-openmake** [OpenMake-Software/ReleaseEngineer#88]
When creating a new Procedure or Function and setting the type to "DMScript in Repository", no repository selector is displayed. it is therefore not possible to create DMScript that is held in a repository.

**Comment by pgibbs-openmake** [comment]
Should now be fixed - requires new build to pick-up

**Comment by sbtaylor15** [comment]
Passed testing in 4/13 build
