### ISSUE TITLE
DM Script error for demo app

### ISSUE THREAD

**Issue by sbtaylor15** [OpenMake-Software/ReleaseEngineer#89]
INFO: Starting deployment #157
INFO: Deploying Application "demoapp" into Environment "demoenv"
INFO: Deploying Component DemoConfig
INFO: Checked out 0 file(s) from repository "demorep"
INFO: Checked out config.txt;0
INFO: Checked out 1 file(s) from repository "demorep"
INFO: Starting Parallel Deployment of Component DemoConfig
INFO: Deploying Component DemoConfig to Server demo_server1
INFO: Deployed File config.txt -> demo_server1:/opt/release-engineer/engine/demo/demoserver1/config.txt
INFO: Deploying Component DemoConfig to Server demo_server1
INFO: Deployed File config.txt -> demo_server1:/opt/release-engineer/engine/demo/demoserver1/config.txt
Exception at line 1 of "action12.dm": Action with the name 'Demo_Amend_Config' already defined

Looks like the Demo_Amend_Config is being include for each component item.

**Comment by pgibbs-openmake** [comment]
This was caused by a bug in the locking mechanism for Linux - this has now been reworked.

**Comment by sbtaylor15** [comment]
Still an issue with build from 4/13

**Comment by pgibbs-openmake** [comment]
I've done north of 10,000 deployments of the demo application with the Linux Engine now - all without hitting this error. Can you confirm that line 227 of thread.cpp looks like this:

 if (!access_lock) {

I'm using a script to continually execute the deployment of the demo application and I'm not hitting this error.

**Comment by sbtaylor15** [comment]
Triple checked the source being used in the build and that line is the same as you indicated.  Running the deployment from a clean machine by just clicking on Deploy for the demoapp.

**Comment by pgibbs-openmake** [comment]
Yep, I agree - just disassembled both libs and the Thread::lock code is the same. So new code is definitely there.

BUT: Did a pull and reinstall of the latest build and set the deployment running in a tight loop:

#!/bin/bash
x=0
c=0
while [[ $x -eq 0 ]]
do
        echo "Running $c"
        ./dm -usr admin -envid 1 -appid 1 -debug 1 | tee /tmp/x.out | grep Failure
        [[ $? -eq 0 ]] && x=1;  # grep matched
        c=$((c+1))
done

This runs the deployment continually until it fails and then it exits with debug output in /tmp/x.out. It's currently up to 3700 deployments and counting without failure.

Before I put the lock fix in I could get this to fail within a couple of attempts.

So, this looks like it's working fine on Fedora 23. What are you testing against?

**Comment by pgibbs-openmake** [comment]
Stopped the script at 11,000 deployments. I cannot get this to fail.

**Comment by sbtaylor15** [comment]
Passed in 4/15 build
