### ISSUE TITLE
Server Side Scripts should run as user "nobody" on Linux

### ISSUE THREAD

**Issue by pgibbs-openmake** [OpenMake-Software/ReleaseEngineer#91]
As the linux engine runs as root, any server-side scripts that are invoked should run as user "nobody" (there has to be a fork/setuid/exec cycle to launch external programs). This will avoid any potential security holes since a user with appropriate admin rights could create a script that runs on the Release Engineer server which would otherwise execute with full superuser permissions.

**Comment by pgibbs-openmake** [comment]
Fix is in - new build and retest required.

**Comment by quinnbailey** [comment]
I'm not sure this is the right way to resolve the security concerns.  "nobody" user is expected, among other things, to own no files.  This is a problem if you want the engine to use an ssh key as a credential.

**Comment by pgibbs-openmake** [comment]
Well, the user defaults to "nobody" - you can change that easily enough. Just create a file with the following in it:

DM_TARGET_USER=restricteduser

and then, in trilogy.conf put the following line after Port=2305

Environment=/path/to/envfile

That will run any external script as "restricteduser" rather than "nobody".

There should really be an application "owner" for Release Engineer.

**Comment by quinnbailey** [comment]
Going to set up a user called "omreleng" that will be the default user for running the scripts.  Technically of course the daemon will continue to run as root.

**Comment by sbtaylor15** [comment]
Retest with latest build.

**Comment by quinnbailey** [comment]
Tested successfully with build 281
