### ISSUE TITLE
Action generated by Ansible has set variable reversed

### ISSUE THREAD

**Issue by quinnbailey** [OpenMake-Software/ReleaseEngineer#94]
Action that is generated by imported Ansible roles has two activities, one to set the set the variables and one to run the procedure.  The set variable activity is setting things as follows:

set server.hostname = ${ansible_server}

whereas it should be:

set  ansible_server = ${server.hostname}

**Comment by sbtaylor15** [comment]
This is correct the ansible_server should override the server.hostname so we can enable just the ansible components to run on a different server than the other components.

**Comment by pgibbs-openmake** [comment]
Yes, but you cannot assign anything to server.hostname. server is an object and hostname is a read only attribute. Running:

set server.hostname = ${ansible_server}

Causes a runtime exception.

**Comment by quinnbailey** [comment]
Yes, when I was using it before it had some issues since server.hostname is a reserved internal variable.  The exact error I saw was as follows:

Runtime error: not a valid set namelist (kind 34)

**Comment by sbtaylor15** [comment]
Removing set variable.  Change ansible.sh to run on RE Server.

**Comment by sbtaylor15** [comment]
Fix in 4/21 build
