### ISSUE TITLE
Generated script for sshexec is missing closing double-quote

### ISSUE THREAD

**Issue by quinnbailey** [OpenMake-Software/ReleaseEngineer#95]
Trying to run an Ansible action saw the following:

INFO: Deploying Component ansible_nginx_crushlovely using Custom Action ansible_nginx_crushlovely_action
/tmp/140728560365136.rsp: line 3: unexpected EOF while looking for matching `"'
/tmp/140728560365136.rsp: line 4: syntax error: unexpected end of file

Looking at the generated .rsp file, the call to sshexec was missing a closing double-quote, just before the redirects for stderr and stdout.

**Comment by sbtaylor15** [comment]
Retest in latest build.  Using temp file to avoid passing parameters to ssh.  instead commands and parameters are put into the temp file.

**Comment by sbtaylor15** [comment]
passed in 5/5 build
