### ISSUE TITLE
Extract zip does run on Windows for demoapp

### ISSUE THREAD

**Issue by sbtaylor15** [OpenMake-Software/ReleaseEngineer#96]

**Comment by sbtaylor15** [comment]
.vbs being translated to .exe instead of being left alone

**Comment by pgibbs-openmake** [comment]
Only place where this happens is in protocol_exec in winlib - if "file.vbs" does not exist, the code checks for "file.cmd", "file.bat" and "file.exe". It sounds like extractzip.vbs (or whatever) is not present or not readable which is causing it to try alternatives...

**Comment by sbtaylor15** [comment]
Permissions are 755 
owner: omreleng 
group: omreleng

**Comment by pgibbs-openmake** [comment]
And are we certain that the path is expanding correctly? The code is in protocol_exec in both winlib.cpp and winlib-unix.cpp. It just does a stat() on the filename and replaces the file extension if stat returns ENOENT. So it's not finding it. We may need to stick a debug line in so we can see what it's looking for...

**Comment by sbtaylor15** [comment]
Yep. I think is slashes being passed to dmtransfer in the wrong direction.

**Comment by pgibbs-openmake** [comment]
That'd do it - on Windows \ and / are interchangeable for stat() etc. On Linux/Unix...nah. We passing \ on a Linux box?

**Comment by sbtaylor15** [comment]
Fixed the slashes and still no joy. I think a command interpreter is needed to run the vbs

**Comment by pgibbs-openmake** [comment]
The winexec code does just that. It checks for .vbs and .js extensions and gets the "invisible agent" to prepend "cscript.exe /nologo <scriptname>" if present.

**Comment by sbtaylor15** [comment]
Passed in 4/22 build
